### PR TITLE
logs bump timeout

### PR DESCRIPTION
**Pull request by sanchaymittal**
- update: tracker type
- add: allSenderedTracker
- add: logs
- chg: bump timeout

## Checklist

- [ ] Test manually on `test-ui` using remote chains.
- [ ] Run load tests.
- [ ] Update documentation if needed.
- [ ] Update CHANGELOG.md.

### CODE REVIEW

**Comment by LayneHaber** [comment]
I'm not sure what the purpose of this PR is outside of bumping the interval timeout

**Review by LayneHaber — COMMENTED** [review]
Need changelog updates, also need to know the impetus for this change and how adding a sender prepared tracker helps solve that. 

Additionally, more unit tests would be helpful here as well

**Review by LayneHaber — CHANGES_REQUESTED** [review]
Need changelog updates, also need to know the impetus for this change and how adding a sender prepared tracker helps solve that.

Additionally, more unit tests would be helpful here as well

**Comment by rhlsthrm** [comment]
Don't think we need this anymore, it was just for debug.

**Pull request closed without merging**
